# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_index1'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index1',
            field=models.IntegerField(default=999, verbose_name='分类的排序'),
        ),
    ]
